### PR TITLE
parsing @types/three definition files

### PR DESCRIPTION
**Pull request by johnrees**
An ongoing effort to parse the contents of https://www.npmjs.com/package/@types/three and generate appropriate files from them

### CODE REVIEW

**Comment by johnrees** [comment]
This page has most of the info we need https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by johnrees** [comment]
In https://github.com/toxicFork/react-three-renderer-fiber/pull/38/commits/51c5e313c2a09f9cfe636f2cd84376d02e475061 I've _started_ generating code with the Typescript compiler. If you want to run it locally, I delete `tsconfig.json` then run `ts-node tools/definitionParser/templates/printer.ts`

This spits out -

```
import * as THREE from "three";
import { AmbientLight } from "three";
import { WrappedEntityDescriptor, WrapperDetails } from "../../common/ObjectWrapper";
interface IAmbientLightProps implements IObject3DProps {
}
```

still a long way to go, but it's been helpful to use http://astexplorer.net and https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast

**Comment by toxicFork** [comment]
I can't wait to give it a try! :D

**Comment by toxicFork** [comment]
Looking at the code, I find it awesome, it will be super efficient especially if the THREEjs api/objects change :)

How would you like to collaborate on this?

- I could work on the core features of R3R-fiber and you can work on this, and when the functionality is fleshed out a bit more we can use this as the ultimate solution for definition generation
  - of course if you need any help with a part of it don't hesitate to ask!
- or if you want me to work on one part of this and you work on another part of it I'd be happy to do that too :)

I can see myself focusing on this too, because once we get all descriptors in there auto-generated it'll be even better than react-three-renderer itself :D

**Comment by johnrees** [comment]
Yes that sounds good @toxicFork 

The first option probably makes the most sense as you know R3R inside-out, so if you continue to work on that I'll generate these 'static' descriptors and catch up with learning about R3R's internals and fiber. 

Of course I am biased 😆 but I think it makes sense to try and switch your focus to working on this fiber implementation because

- Typescript intellisense will be able to help a lot of developers who are discovering the library. A hosted split-screen editor like [monaco](https://github.com/Microsoft/monaco-editor) and THREE canvas could be a powerful learning tool

- The performance benefits of utilising fiber over stack will be significant

**Comment by johnrees** [comment]
Will try and come back to this soon, I found a nice little library that might make this easier too https://dsherret.github.io/ts-simple-ast/setup/adding-source-files#by-structure

**Comment by toxicFork** [comment]
Yes that library looks super useful, it will be worth giving it a try to see what can be done, or if we can find a way to interact directly with the internals of typescript to write "more raw" stuff if necessary, but hopefully for the component definitions nothing too fancy will be necessary 😅

**Comment by Methuselah96** [comment]
I will go ahead and say that I don't think the @types/three definitions are stable enough to use for generating descriptors. I've contributed to @types/three myself. From what I've seen, it does not stay up-to-date and it is too fragile to be trusted. I think it will be more work in the long-run to try to do it this way and makes us unnecessarily dependent on something that is ultimately out of our control.

**Comment by toxicFork** [comment]
Good arguments in previous commit - closing.

**Pull request closed without merging**
