### PR TITLE
Finish writing all geometry descriptors

### PR DESCRIPTION
**Pull request by Methuselah96**

### CODE REVIEW

**Comment by Methuselah96** [comment]
`ParametricBufferGeometry` was missing from the types package so I couldn't add it.

**Comment by toxicFork** [comment]
Very nice way of implementing this! :)

**Comment by Methuselah96** [comment]
Did even more simplification and should be as type-safe as possible. I'll be able to simplify `createGeometryDescriptor.ts` a lot more when we can use TypeScript 3.0 (right now there seems to be an error with @types/webvr-api and TypeScript 3.0 (see https://github.com/Microsoft/TypeScript/issues/26038)).

**Comment by toxicFork** [comment]
This is awesome!

**Comment by toxicFork** [comment]
And looking forward to TS3.1 too

**Pull request merged**
